### ISSUE TITLE
Keep logging

### ISSUE THREAD

**Issue by AlexDicy** [ALCC01/nodeogram#6]
I just tried yesterday with the basic example wrote in the Readme file, anyway when I started the bot typing /start (in Telegram) nodeogram was logging every second this:
(Can't use code styling as the mobile website doesn't permit it)

 [{"update_id":198597148,"message":{"message_id":17,"from":{"id":168473527,"first_name":"HAlex™","username":"HAlexTM"},"chat":{"id":168473527,"first_name":"HAlex™","username":"HAlexTM","type":"private"},"date":1474348978,"text":"/start","entities":[{"type":"bot_command","offset":0,"length":6}]}}]
[ReferenceError: Keyboard is not defined]

**Comment by ALCC01** [comment]
Hi, the first line of logs is a known issue that will be fixed in the next pre-release, please see pr #4.

The second one (`[ReferenceError: Keyboard is not defined]`), however, is an error generated from your own code and not from nodeogram itself.

**Comment by AlexDicy** [comment]
It's bad 'cause I didn't edit the code in the example, anyway thanks for explaining
